// <auto-generated />
using System;
using Gma.Modules.Notifications.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gma.Modules.Notifications.Persistence.SqlServerMigrations.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260804010054_AddResumableNotificationHistoryClose")]
    partial class AddResumableNotificationHistoryClose
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.NotificationBroadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Audience");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Severity");

                    b.Property<long>("StreamSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StreamSequence"));

                    b.HasKey("Id");

                    b.HasIndex("StreamSequence");

                    b.HasIndex("Audience", "ScopeId", "OccurredAtUtc");

                    b.HasIndex("Audience", "ScopeId", "StreamSequence");

                    b.ToTable("notification_broadcasts", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeliveryTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("DeliveryTag");

                    b.Property<string>("LastCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("ScopeId", "Status", "CreatedAtUtc");

                    b.HasIndex("ScopeId", "NotificationId", "DeliveryTag", "Provider")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc", "LockedUntilUtc", "CreatedAtUtc");

                    b.ToTable("deliveries", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.NotificationDeliveryRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("DeliveryTag");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "DeliveryTag")
                        .IsUnique();

                    b.HasIndex("ScopeId", "Provider", "IsActive");

                    b.ToTable("delivery_routes", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TagKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TagKey");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "UserId", "Enabled");

                    b.HasIndex("ScopeId", "UserId", "TagKey")
                        .IsUnique();

                    b.ToTable("preferences", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.NotificationTagDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TagKey");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "Key")
                        .IsUnique();

                    b.HasIndex("ScopeId", "Kind", "IsActive", "Key");

                    b.ToTable("tag_definitions", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeliveryPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("respect-preferences");

                    b.Property<bool>("IsInboxVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserId");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Severity");

                    b.Property<long>("StreamSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StreamSequence"));

                    b.HasKey("Id");

                    b.HasIndex("StreamSequence");

                    b.HasIndex("ScopeId", "StreamSequence");

                    b.HasIndex("ScopeId", "IsInboxVisible", "CreatedAtUtc");

                    b.HasIndex("ScopeId", "Recipient", "OccurredAtUtc");

                    b.HasIndex("ScopeId", "Recipient", "ReadAtUtc");

                    b.HasIndex("ScopeId", "Recipient", "StreamSequence");

                    b.ToTable("user_notifications", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationBroadcastRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BroadcastId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ReadAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("RecipientId");

                    b.Property<string>("RecipientKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("RecipientKind");

                    b.Property<string>("RecipientScope")
                        .IsRequired()
                        .HasMaxLength(135)
                        .HasColumnType("nvarchar(135)");

                    b.HasKey("Id");

                    b.HasIndex("BroadcastId", "RecipientScope", "RecipientKind", "Recipient")
                        .IsUnique();

                    b.HasIndex("RecipientScope", "RecipientKind", "Recipient", "BroadcastId");

                    b.ToTable("notification_broadcast_reads", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("ScopeId", "CompletedAtUtc");

                    b.HasIndex("ScopeId", "DeliveryId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("delivery_attempts", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryBatchCloseOperation", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatchSize")
                        .HasColumnType("int");

                    b.Property<int>("CompletedBatchCount")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ProofVersion")
                        .HasColumnType("int");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ScopeId", "OperationId");

                    b.HasIndex("ScopeId", "Namespace", "Digest")
                        .IsUnique();

                    b.ToTable("notification_history_batch_close_operations", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_notification_history_batch_close_operations_batch", "\"BatchSize\" >= 1 AND \"BatchSize\" <= 1000");

                            t.HasCheckConstraint("CK_notification_history_batch_close_operations_progress", "\"RemovedRecordCount\" >= 0 AND \"CompletedBatchCount\" >= 0 AND \"ProofVersion\" >= 1");

                            t.HasCheckConstraint("CK_notification_history_batch_close_operations_versions", "\"ExpectedVersion\" >= 0 AND \"ResultingVersion\" > \"ExpectedVersion\"");
                        });
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryBatchCloseReceipt", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("int");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<int>("RemovalProofVersion")
                        .HasColumnType("int");

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ScopeId", "OperationId");

                    b.HasIndex("ScopeId", "Namespace", "Digest")
                        .IsUnique();

                    b.ToTable("notification_history_batch_close_receipts", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_notification_history_batch_close_receipts_progress", "\"RemovedRecordCount\" >= 0 AND \"CompletedBatchCount\" >= 0 AND \"RemovalProofVersion\" >= 1");

                            t.HasCheckConstraint("CK_notification_history_batch_close_receipts_version", "\"ResultingVersion\" >= 1");
                        });
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryCloseReceipt", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RemovedRecordCount")
                        .HasColumnType("int");

                    b.Property<string>("RemovedRecordIdsSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "OperationId");

                    b.HasIndex("ScopeId", "Namespace", "Digest", "CompletedAtUtc");

                    b.ToTable("notification_history_close_receipts", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_notification_history_close_receipts_count", "\"RemovedRecordCount\" >= 0");

                            t.HasCheckConstraint("CK_notification_history_close_receipts_version", "\"ResultingVersion\" >= 1");
                        });
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryReferenceState", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Digest")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid?>("CloseOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloseRequestSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "Namespace", "Digest");

                    b.HasIndex("ScopeId", "IsClosed", "ClosedAtUtc");

                    b.ToTable("notification_history_reference_states", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_notification_history_reference_states_version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.UserNotificationReference", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Namespace")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Digest")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.HasKey("ScopeId", "NotificationId", "Namespace", "Digest");

                    b.HasIndex("NotificationId");

                    b.HasIndex("ScopeId", "Namespace", "Digest", "NotificationId");

                    b.ToTable("user_notification_references", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.UserNotificationTag", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TagKey");

                    b.HasKey("ScopeId", "NotificationId", "Key");

                    b.HasIndex("NotificationId");

                    b.HasIndex("ScopeId", "Key", "NotificationId");

                    b.ToTable("user_notification_tags", "notifications");
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.NotificationBroadcast", b =>
                {
                    b.OwnsOne("Gma.Modules.Notifications.Domain.ValueObjects.NotificationContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("NotificationBroadcastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .HasMaxLength(4096)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Body");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Title");

                            b1.HasKey("NotificationBroadcastId");

                            b1.ToTable("notification_broadcasts", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationBroadcastId");
                        });

                    b.OwnsOne("Gma.Modules.Notifications.Domain.ValueObjects.NotificationSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("NotificationBroadcastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Module");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Name");

                            b1.Property<int>("Version")
                                .HasColumnType("int")
                                .HasColumnName("Version");

                            b1.HasKey("NotificationBroadcastId");

                            b1.HasIndex("Module", "Name", "Version");

                            b1.ToTable("notification_broadcasts", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationBroadcastId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.NotificationDelivery", b =>
                {
                    b.HasOne("Gma.Modules.Notifications.Domain.Aggregates.UserNotification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.UserNotification", b =>
                {
                    b.OwnsOne("Gma.Modules.Notifications.Domain.ValueObjects.NotificationContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("UserNotificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .HasMaxLength(4096)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Body");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Title");

                            b1.HasKey("UserNotificationId");

                            b1.ToTable("user_notifications", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("UserNotificationId");
                        });

                    b.OwnsOne("Gma.Modules.Notifications.Domain.ValueObjects.NotificationSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("UserNotificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Module");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Name");

                            b1.Property<int>("Version")
                                .HasColumnType("int")
                                .HasColumnName("Version");

                            b1.HasKey("UserNotificationId");

                            b1.HasIndex("Module", "Name", "Version");

                            b1.ToTable("user_notifications", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("UserNotificationId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationDeliveryAttempt", b =>
                {
                    b.HasOne("Gma.Modules.Notifications.Domain.Aggregates.NotificationDelivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryBatchCloseOperation", b =>
                {
                    b.HasOne("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryReferenceState", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "Namespace", "Digest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryBatchCloseReceipt", b =>
                {
                    b.HasOne("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryReferenceState", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "Namespace", "Digest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.UserNotificationReference", b =>
                {
                    b.HasOne("Gma.Modules.Notifications.Domain.Aggregates.UserNotification", null)
                        .WithMany("References")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gma.Modules.Notifications.Domain.Entities.NotificationHistoryReferenceState", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "Namespace", "Digest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Entities.UserNotificationTag", b =>
                {
                    b.HasOne("Gma.Modules.Notifications.Domain.Aggregates.UserNotification", null)
                        .WithMany("Tags")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.Notifications.Domain.Aggregates.UserNotification", b =>
                {
                    b.Navigation("References");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
